name: Go

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 5"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Stats
      run: go run github.com/arran4/github-level/cmd/stats

    - name: Text Levels
      run: go run github.com/arran4/github-level/cmd/leveltext

#    - name: Create Badge Files
#      run: go run github.com/arran4/github-level/cmd/badge

    - name: Output shield
      run: go run github.com/arran4/github-level/cmd/sheild | tee shield.txt

    - name: PR shield
      run: go run github.com/arran4/github-level/cmd/prsheild
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
